import { createFileRoute } from "@tanstack/react-router";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

import { BreakdownTable } from "@/components/pulse/breakdown-table";
import { KpiCard } from "@/components/pulse/kpi-card";
import { PageIntro, Panel, Reveal } from "@/components/pulse/primitives";
import {
  delta,
  formatDayLabel,
  getAverageDealSize,
  getCampaignPerformance,
  getChannelPerformance,
  getRevenuePerMessage,
  getSeries,
  getTeamPerformance,
  money,
  number,
  type SeriesPoint,
} from "@/lib/pulse/analytics";
import { useAnalytics } from "@/lib/pulse/filters";

export const Route = createFileRoute("/_shell/analytics/revenue")({
  head: () => ({
    meta: [
      { title: "Revenue Analytics — PULSE" },
      {
        name: "description",
        content: "Revenue generated by outreach: closed-won value over time, average deal size, revenue per message and ROI by campaign.",
      },
      { property: "og:title", content: "Revenue Analytics — PULSE" },
      { property: "og:description", content: "Attribute revenue back to the messages that produced it." },
    ],
  }),
  component: RevenueAnalytics,
});

function RevenueTooltip({ active, payload }: { active?: boolean; payload?: { payload?: SeriesPoint }[] }) {
  const p = payload?.[0]?.payload;
  if (!active || !p) return null;
  return (
    <div className="rounded-lg border border-border-strong bg-popover/95 p-3 text-xs shadow-lift backdrop-blur">
      <p className="font-medium">{formatDayLabel(p.date)}</p>
      <p className="num mt-1.5 font-medium text-positive">{money(p.revenue)}</p>
      <p className="num text-muted-foreground">{number(p.deals)} deals closed</p>
    </div>
  );
}

function RevenueAnalytics() {
  const { totals, previousTotals, facts, granularity } = useAnalytics();
  const series = getSeries(facts, granularity);

  return (
    <div className="space-y-6">
      <PageIntro title="Revenue Analytics" subtitle="What did outreach actually earn, and which spend returned it?" />

      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <KpiCard
          label="Revenue"
          value={totals.revenue}
          format={(v) => money(v)}
          delta={delta(totals.revenue, previousTotals.revenue)}
          emphasis="primary"
        />
        <KpiCard label="Deals closed" value={totals.deals} delta={delta(totals.deals, previousTotals.deals)} />
        <KpiCard
          label="Average deal size"
          value={getAverageDealSize(totals)}
          format={(v) => money(v)}
          delta={delta(getAverageDealSize(totals), getAverageDealSize(previousTotals))}
        />
        <KpiCard
          label="Revenue per message"
          value={getRevenuePerMessage(totals)}
          format={(v) => `$${v.toFixed(2)}`}
          delta={delta(getRevenuePerMessage(totals), getRevenuePerMessage(previousTotals))}
          hint="Outreach efficiency"
        />
      </div>

      <Reveal>
        <Panel title="Revenue over time" description="Closed-won contract value across the selected period.">
          <div className="h-[300px] w-full">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={series} margin={{ top: 8, right: 8, bottom: 0, left: 4 }}>
                <defs>
                  <linearGradient id="pulse-revenue" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor="var(--chart-2)" stopOpacity={0.3} />
                    <stop offset="100%" stopColor="var(--chart-2)" stopOpacity={0} />
                  </linearGradient>
                </defs>
                <CartesianGrid stroke="var(--border)" strokeDasharray="3 3" vertical={false} />
                <XAxis dataKey="label" tick={{ fill: "var(--muted-foreground)", fontSize: 11 }} axisLine={false} tickLine={false} minTickGap={16} />
                <YAxis
                  tickFormatter={(v: number) => money(v, { compact: true })}
                  tick={{ fill: "var(--muted-foreground)", fontSize: 11 }}
                  axisLine={false}
                  tickLine={false}
                  width={64}
                />
                <Tooltip content={<RevenueTooltip />} cursor={{ stroke: "var(--border-strong)" }} />
                <Area type="monotone" dataKey="revenue" stroke="var(--chart-2)" strokeWidth={1.75} fill="url(#pulse-revenue)" dot={false} animationDuration={520} />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </Panel>
      </Reveal>

      <Reveal>
        <Panel title="Return by campaign" description="Revenue against campaign cost.">
          <BreakdownTable rows={getCampaignPerformance(facts)} labelHeader="Campaign" showRoi />
        </Panel>
      </Reveal>

      <div className="grid gap-4 xl:grid-cols-2">
        <Reveal>
          <Panel title="Revenue by channel">
            <BreakdownTable rows={getChannelPerformance(facts)} labelHeader="Channel" />
          </Panel>
        </Reveal>
        <Reveal delay={60}>
          <Panel title="Revenue by team member">
            <BreakdownTable rows={getTeamPerformance(facts)} labelHeader="Member" rank />
          </Panel>
        </Reveal>
      </div>
    </div>
  );
}
