/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellCampaignsRouteImport } from './routes/_shell.campaigns'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellIntegrationsRouteImport } from './routes/_shell.integrations'
import { Route as ShellLeadsRouteImport } from './routes/_shell.leads'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellTeamRouteImport } from './routes/_shell.team'
import { Route as ShellAnalyticsConversionRouteImport } from './routes/_shell.analytics.conversion'
import { Route as ShellAnalyticsOutreachRouteImport } from './routes/_shell.analytics.outreach'
import { Route as ShellAnalyticsRepliesRouteImport } from './routes/_shell.analytics.replies'
import { Route as ShellAnalyticsRevenueRouteImport } from './routes/_shell.analytics.revenue'
import { Route as ShellCreatorsLongRouteImport } from './routes/_shell.creators.long'
import { Route as ShellCreatorsShortRouteImport } from './routes/_shell.creators.short'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellCampaignsRoute = ShellCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIntegrationsRoute = ShellIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLeadsRoute = ShellLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTeamRoute = ShellTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnalyticsConversionRoute =
  ShellAnalyticsConversionRouteImport.update({
    id: '/analytics/conversion',
    path: '/analytics/conversion',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellAnalyticsOutreachRoute = ShellAnalyticsOutreachRouteImport.update({
  id: '/analytics/outreach',
  path: '/analytics/outreach',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnalyticsRepliesRoute = ShellAnalyticsRepliesRouteImport.update({
  id: '/analytics/replies',
  path: '/analytics/replies',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnalyticsRevenueRoute = ShellAnalyticsRevenueRouteImport.update({
  id: '/analytics/revenue',
  path: '/analytics/revenue',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCreatorsLongRoute = ShellCreatorsLongRouteImport.update({
  id: '/creators/long',
  path: '/creators/long',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCreatorsShortRoute = ShellCreatorsShortRouteImport.update({
  id: '/creators/short',
  path: '/creators/short',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns': typeof ShellCampaignsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/integrations': typeof ShellIntegrationsRoute
  '/leads': typeof ShellLeadsRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/team': typeof ShellTeamRoute
  '/analytics/conversion': typeof ShellAnalyticsConversionRoute
  '/analytics/outreach': typeof ShellAnalyticsOutreachRoute
  '/analytics/replies': typeof ShellAnalyticsRepliesRoute
  '/analytics/revenue': typeof ShellAnalyticsRevenueRoute
  '/creators/long': typeof ShellCreatorsLongRoute
  '/creators/short': typeof ShellCreatorsShortRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns': typeof ShellCampaignsRoute
  '/dashboard': typeof ShellDashboardRoute
  '/integrations': typeof ShellIntegrationsRoute
  '/leads': typeof ShellLeadsRoute
  '/reports': typeof ShellReportsRoute
  '/settings': typeof ShellSettingsRoute
  '/team': typeof ShellTeamRoute
  '/analytics/conversion': typeof ShellAnalyticsConversionRoute
  '/analytics/outreach': typeof ShellAnalyticsOutreachRoute
  '/analytics/replies': typeof ShellAnalyticsRepliesRoute
  '/analytics/revenue': typeof ShellAnalyticsRevenueRoute
  '/creators/long': typeof ShellCreatorsLongRoute
  '/creators/short': typeof ShellCreatorsShortRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/campaigns': typeof ShellCampaignsRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/integrations': typeof ShellIntegrationsRoute
  '/_shell/leads': typeof ShellLeadsRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/team': typeof ShellTeamRoute
  '/_shell/analytics/conversion': typeof ShellAnalyticsConversionRoute
  '/_shell/analytics/outreach': typeof ShellAnalyticsOutreachRoute
  '/_shell/analytics/replies': typeof ShellAnalyticsRepliesRoute
  '/_shell/analytics/revenue': typeof ShellAnalyticsRevenueRoute
  '/_shell/creators/long': typeof ShellCreatorsLongRoute
  '/_shell/creators/short': typeof ShellCreatorsShortRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/dashboard'
    | '/integrations'
    | '/leads'
    | '/reports'
    | '/settings'
    | '/team'
    | '/analytics/conversion'
    | '/analytics/outreach'
    | '/analytics/replies'
    | '/analytics/revenue'
    | '/creators/long'
    | '/creators/short'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns'
    | '/dashboard'
    | '/integrations'
    | '/leads'
    | '/reports'
    | '/settings'
    | '/team'
    | '/analytics/conversion'
    | '/analytics/outreach'
    | '/analytics/replies'
    | '/analytics/revenue'
    | '/creators/long'
    | '/creators/short'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/campaigns'
    | '/_shell/dashboard'
    | '/_shell/integrations'
    | '/_shell/leads'
    | '/_shell/reports'
    | '/_shell/settings'
    | '/_shell/team'
    | '/_shell/analytics/conversion'
    | '/_shell/analytics/outreach'
    | '/_shell/analytics/replies'
    | '/_shell/analytics/revenue'
    | '/_shell/creators/long'
    | '/_shell/creators/short'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/campaigns': {
      id: '/_shell/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof ShellCampaignsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/integrations': {
      id: '/_shell/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof ShellIntegrationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/leads': {
      id: '/_shell/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof ShellLeadsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/team': {
      id: '/_shell/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof ShellTeamRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analytics/conversion': {
      id: '/_shell/analytics/conversion'
      path: '/analytics/conversion'
      fullPath: '/analytics/conversion'
      preLoaderRoute: typeof ShellAnalyticsConversionRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analytics/outreach': {
      id: '/_shell/analytics/outreach'
      path: '/analytics/outreach'
      fullPath: '/analytics/outreach'
      preLoaderRoute: typeof ShellAnalyticsOutreachRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analytics/replies': {
      id: '/_shell/analytics/replies'
      path: '/analytics/replies'
      fullPath: '/analytics/replies'
      preLoaderRoute: typeof ShellAnalyticsRepliesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analytics/revenue': {
      id: '/_shell/analytics/revenue'
      path: '/analytics/revenue'
      fullPath: '/analytics/revenue'
      preLoaderRoute: typeof ShellAnalyticsRevenueRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/creators/long': {
      id: '/_shell/creators/long'
      path: '/creators/long'
      fullPath: '/creators/long'
      preLoaderRoute: typeof ShellCreatorsLongRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/creators/short': {
      id: '/_shell/creators/short'
      path: '/creators/short'
      fullPath: '/creators/short'
      preLoaderRoute: typeof ShellCreatorsShortRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellCampaignsRoute: typeof ShellCampaignsRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellIntegrationsRoute: typeof ShellIntegrationsRoute
  ShellLeadsRoute: typeof ShellLeadsRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellTeamRoute: typeof ShellTeamRoute
  ShellAnalyticsConversionRoute: typeof ShellAnalyticsConversionRoute
  ShellAnalyticsOutreachRoute: typeof ShellAnalyticsOutreachRoute
  ShellAnalyticsRepliesRoute: typeof ShellAnalyticsRepliesRoute
  ShellAnalyticsRevenueRoute: typeof ShellAnalyticsRevenueRoute
  ShellCreatorsLongRoute: typeof ShellCreatorsLongRoute
  ShellCreatorsShortRoute: typeof ShellCreatorsShortRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellCampaignsRoute: ShellCampaignsRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellIntegrationsRoute: ShellIntegrationsRoute,
  ShellLeadsRoute: ShellLeadsRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellTeamRoute: ShellTeamRoute,
  ShellAnalyticsConversionRoute: ShellAnalyticsConversionRoute,
  ShellAnalyticsOutreachRoute: ShellAnalyticsOutreachRoute,
  ShellAnalyticsRepliesRoute: ShellAnalyticsRepliesRoute,
  ShellAnalyticsRevenueRoute: ShellAnalyticsRevenueRoute,
  ShellCreatorsLongRoute: ShellCreatorsLongRoute,
  ShellCreatorsShortRoute: ShellCreatorsShortRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
